version: '3.8'

services:
  weddineo-backend:
    image: weddineo/weddineo-backend
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  weddineo-frontend.web:
    image: weddineo/weddineo-frontend
    build:
      context: .
      dockerfile: ./weddineo-frontend/Dockerfile
      args: 
        NG_BUILD_CONF: local
    ports:
      - 9090:80
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb


