version: '3.8'

services:
  dbpostgresql:
    image: postgres
    container_name: postgresDatabase
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=weddineo
  weddineo-core:
    image: weddineo/weddineo-core
    build:
       context: .
       dockerfile: ./weddineo-core/Dockerfile
       args: 
        JAR_FILE_PATH: ./weddineo-core/target/*.jar
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  weddineo-frontend.web:
    image: weddineo/weddineo-frontend
    build:
      context: .
      dockerfile: ./weddineo-frontend/Dockerfile
      args: 
        NG_BUILD_CONF: local
    ports:
      - "9090:80"
    depends_on:
      - weddineo-core



