spring:
  profiles:
    active: '@spring.profiles.active@'
  datasource:
    url: jdbc:postgresql://localhost:5432/weddineo
    username: postgres
    password: password
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
server:
  servlet:
    context-path: /api
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
firebase:
  datebase-url: https://weddineo-236fc.firebaseio.com
  credentials-path: "${WEDDINEO_FIREBASE_CREDENTIALS_PATH}"

weddineo:
  build-version: '@project.version@'